// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { StartScanStartScanPostError, StartScanStartScanPostResponse, StopScanStopScanPostError, StopScanStopScanPostResponse, GetNodesNodesGetError, GetNodesNodesGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Start Scan
 */
export const startScanStartScanPost = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<StartScanStartScanPostResponse, StartScanStartScanPostError, ThrowOnError>({
        ...options,
        url: '/start_scan'
    });
};

/**
 * Stop Scan
 */
export const stopScanStopScanPost = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<StopScanStopScanPostResponse, StopScanStopScanPostError, ThrowOnError>({
        ...options,
        url: '/stop_scan'
    });
};

/**
 * Get Nodes
 */
export const getNodesNodesGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetNodesNodesGetResponse, GetNodesNodesGetError, ThrowOnError>({
        ...options,
        url: '/nodes'
    });
};