// This file is auto-generated by @hey-api/openapi-ts

export type NetworkSummary = {
    description: string;
};

export type Node = {
    ip: string;
    mac_address?: (string | null);
    hostname?: (string | null);
    os?: (string | null);
    open_ports?: Array<{
        [key: string]: (number | string);
    }>;
    last_seen: string;
    status: string;
    other_info?: {
        [key: string]: (string);
    };
    connected_to?: Array<(string)>;
    hop_distance?: (number | null);
    node_type?: (string | null);
};

export type StartScanStartScanPostResponse = (unknown);

export type StartScanStartScanPostError = unknown;

export type StopScanStopScanPostResponse = (unknown);

export type StopScanStopScanPostError = unknown;

export type GetNodesNodesGetResponse = (Array<Node>);

export type GetNodesNodesGetError = unknown;

export type GetNodesDescriptionNetworkSummaryGetResponse = (NetworkSummary);

export type GetNodesDescriptionNetworkSummaryGetError = unknown;